### ISSUE TITLE
GreaterThan is incorrect for certain numbers

### ISSUE THREAD

**Issue by Jcparkyn** [unional/type-plus#161]
There seems to be an issue with the `GreaterThan` implementation, so it is wrong for certain combinations of numbers (but none of the numbers tested in the .spec.ts file).

Example ([TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgcSgUwIYzVAKgCwwDs4BfOAMyghDgCIYBPMNAWjABsBXAZzoG4AUIKYs42HjACMcALwp0WHAWIAeKQAYANHCkBOAHxwA9MbgBhaOgDGMEczTi0kgExyFmbHkJF1enZpGpnAASmgwXFBEPJQYHDyOAEZc8Dz4EFwcACZwiY4wUFxoQA)):

```ts
import { GreaterThan } from "type-plus";

type test1 = GreaterThan<10, 19> // Correct (false)
type test2 = GreaterThan<19, 10> // Incorrect (returns false but should be true)
```

The issue seems to be in the implementation of `OnDigitArray`, which as far as I can tell should just look like this:

```ts
type OnDigitArray<DA extends number[], DB extends number[]> = (
  Equal<Head<DA>, Head<DB>> extends true
    ? OnDigitArray<Tail<DA>, Tail<DB>>
    : Digit.GreaterThan<Head<DA>, Head<DB>>
)
```

**Comment by unional** [comment]
Thank you! That logic looks like some leftovers when I was implementing during TDD, the tests didn't catch that.

Would you be interested in creating a PR for this?
