### ISSUE TITLE
Extend GreaterThan to support negative numbers

### ISSUE THREAD

**Issue by Jcparkyn** [unional/type-plus#162]
It appears to be quite easy to extend the implementation of `GreaterThan` to also support negative numbers, which would make it significantly more useful.

[Here's my rough implementation](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQHYBMA0cCiBHAVwEMAbbASQGcAFCS4GYANwFMLKB1ACwhLbgByEGNgAiwAOYNkUKEQCe2ALJEAHtmpF0AGRYAzEXAASLLWMkNsAFSLAScAL5w9UCCDgAiGPLAsAtGAkBJQeANwAUOHevnASMFYslDAAjHAAvHAA4lCmMCxQVlxEqDiqeRgs6AA8ydgATAB8UT4ssfGJMHXpWTlEeQVFJWUsFdV12MlN0a1xCUkAzN3ZufmFxaXl6JVVfrVwk80xsx0ALEu9-WtDm9t7u1MtbXMwAKznKwPrw6M743D3hxm7SSADZ3n1VoMNiMttVdtg-I1IixVJBYHBpj0PldoT9kHAUZtKHBUAQQAAjfLYABCBO+6GJpIpVLgADFbPYMqgWKwoA10uE4CgMFUqNxeCwqsgGuxxXwqtSGvzCTDiXpSJRWgB+NkcuAALkFJLJlKgdKJKDgOvZdgNRqZpvNqrgtOtesNQvwxBIUppyvpxJgUAI2ucGtaHuF1SotHojFYUplgmEopodAYzEliqVTowgeDoaDIbtQrQ1SEMFTsYzCelSZj6fjWZzKrzGILVrDJE1JajVcbmcT7GrTYVLYD7eLOoA8qgR5m5ZLkH7e7P56xFwrsNLIoC4GuBxuePL8a2GcbmVAabnzw78vyMgAKI2s1wgAQm-LIcmURM34nAKgej5HAoj4jqYH-hepoANoALpWi+b4fpe36-oqUGAcBZqiK6oG0mejKflA8GIUKKiqFUYEwQA5HwqBxFwNFwWI1K0fRjHMf6FpYSBSidvxhHQSBWpGpoOj6JWYHKNgAAM3HOrxZrUJBOoqaeE53iRCGiUK4m6AYVHUjJcDyZhQEgSpeFWVBWmkbp+6oOIUgwDIcjyFU6kaLhTRCvqJI8iB-ncryRrBYFZrhaFfkBbyBqxfkYUJZFyVJSFQWpQAlJEmKzs50iyAoVEaRadksfhtnEfBD5wM+nqEKQVQmFoxVJs11Q+QpbZFiwRpCjOTkWK5hUeTYditdYHJGUqfXxflMAAHTLBCnyoE1pgddK2DtdNTTZXuVhQKASiAcEADKkhrQIUFJEdDE1ddQkAAZ+AAJAgSlwDkSQOE9Ro6t98D+QIER7q+bgoaaaFVI9mnETV81uQoC3gyAZ1BoBEhVIdx2nZQF0SGtT3vQIv1KkAA), including the fix from #161.

**Comment by unional** [comment]
That's a great idea. I didn't think about handling negative numbers because the "number generator" (`array.length`) does not support negative number.

Your implementation looks good but likely need some tweaks. If you are interested to create a PR for it, feel free to give it a try.
Or you can try the PR for #161 and I'll at this support after that.
