### ISSUE TITLE
`IsArray<never[]>` returns `false`

### ISSUE THREAD

**Issue by PCOffline** [unional/type-plus#353]
I don't know if it's by design, but both `IsTuple` and `IsArray` return `false` for `never[]` in the latest version of `type-plus`.

**Comment by PCOffline** [comment]
These are the relevant tests that don't cover the `never[]` case (or, as a matter of fact, any complex cases)
https://github.com/unional/type-plus/blob/156bbec26ec27153153ffc1ad85a18894610efc4/type-plus/ts/array/array_type.spec.ts#L4-L6

**Comment by unional** [comment]
For `IsTuple`, `never[]` returning `never` is correct because it specifically exclude array as tuple is a more specialized form.

For `IsArray`, that's probably a bug. But do you have a specific use case for that?

**Comment by PCOffline** [comment]
Well, the nature of `never` means it's not commonly used, so it's not critical.

**Comment by PCOffline** [comment]
I may be missing something, but why a more naive solution such as 
```ts
type IsArray<T, Then = true, Else = false> = IsNever<
  T,
  Else,
  IsAny<T, Else, T extends AnyArray ? Then : Else>
>;
```

isn't sufficient?

**Comment by unional** [comment]
The problem is with the distributive nature of TypeScript.

You can try it out with the tests in https://github.com/unional/type-plus/blob/main/type-plus/ts/array/array_type.spec.ts etc.

**Comment by PCOffline** [comment]
I gave it a few shots, but I clearly lack the knowledge. I have no idea how the magic trick of `[any[]] extends [T]` even makes sense, or what `[T] extends [readonly any[]]` even means.

**Comment by unional** [comment]
That is a workaround in TypeScript to avoid the union distribution took place. 

Just think of it as a technique you can use when doing your type level programming.
