### ISSUE TITLE
Type errors in `types/Generate.d.ts`

### ISSUE THREAD

**Issue by schickling** [unional/type-plus#82]
Using the latest version of `type-plus` (3.4.0) I'm seeing the following type errors:

![image](https://user-images.githubusercontent.com/1567498/99875819-c4df9880-2bf2-11eb-81f6-f6f29bc83c48.png)

![image](https://user-images.githubusercontent.com/1567498/99875829-d1fc8780-2bf2-11eb-8687-bb17e5a4e522.png)

**Comment by unional** [comment]
Thanks for reporting.

During refactoring, `Tuple.Tail` is moved out as `Tail`, so VS Code can't figure out what that is thus ignoring it.
Causing it to think the `Generate` type is referencing itself.

btw, this will be simplified and improved in TS 4.1 :)
